### ISSUE TITLE
Review security requirements for use cases using misuse case diagrams.

### ISSUE THREAD

**Issue by kteja-ayinala** [kteja-ayinala/SW-Assurance-Term-Project#1]

**Comment by Aaron-Kirby** [comment]
1. User saving to cloud
- Misuser steals info
2. User downloading from cloud
- Misuser steals it or deletes, modifies
3. Backing-up database
- Misuser steals it, or deletes it, modifies
4. Maintain authentication details
- Change authentication, unauthorized access
5. Audit workflow (version control)
- Steal process history

**Comment by SindhuraBonthu** [comment]
Updated misuse Cases
